#pragma once

#define TEXT_BLACK 0x00
#define TEXT_BLUE 0x01
#define TEXT_GREEN 0x02
#define TEXT_CYAN 0x03
#define TEXT_RED 0x04
#define TEXT_MAGENTA 0x05
#define TEXT_BROWN 0x06
#define TEXT_LIGHTGRAY 0x07
#define TEXT_DARKGRAY 0x08
#define TEXT_LIGHTBLUE 0x09
#define TEXT_LIGHTGREEN 0x0A
#define TEXT_LIGHTCYAN 0x0B
#define TEXT_LIGHTRED 0xC
#define TEXT_LIGHTMAGENTA 0x0D
#define TEXT_YELLOW 0x0E
#define TEXT_WHITE 0x0F

#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_CYAN 0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_LIGHTGRAY 0x70
#define BACKGROUND_BLINKINGBLACK 0x80
#define BACKGROUND_BLINKINGBLUE 0x90
#define BACKGROUND_BLINKINGGREEN 0xA0
#define BACKGROUND_BLINKINGCYAN 0xB0
#define BACKGROUND_BLINKINGRED 0xC0
#define BACKGROUND_BLINKINGMAGENTA 0xD0
#define BACKGROUND_BLINKINGYELLOW 0xE0
#define BACKGROUND_WHITE 0xF0